### ISSUE TITLE
Help with slow prompt

### ISSUE THREAD

**Issue by mathomp4** [zandrmartin/git-status-prompt#2]
@zandrmartin I recently found your program and was excited. I forked and changed it a bit to make it work with tcsh (changing the color codes). But, after building it, it runs really slowly in my repository:
```
(1084) $ /usr/bin/time -p env LD_LIBRARY_PATH=/discover/swdev/mathomp4/lib git_status_prompt
[%{%}dev-Icarus-UNSTABLE-RanlibFix-ESMF7%{%}|%{%}_1%{%}]
real 46.54
user 1.54
sys 3.30
```
Almost a minute! Compared to a normal `git status` call:
```
(1085) $ /usr/bin/time -p git status 
On branch dev-Icarus-UNSTABLE-RanlibFix-ESMF7
Your branch is up-to-date with 'origin/dev-Icarus-UNSTABLE-RanlibFix-ESMF7'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/log.ParallelInstall

nothing added to commit but untracked files present (use "git add" to track)
real 3.49
user 0.08
sys 0.48
```
So, I've done something bad. I thought maybe I built libgit2 wrong, so I spent sometime and figured out how to get libssh2 built and linked, and built libgit2 as a `Release` and not `Debug`. No help, really.

Perhaps it is this issue https://github.com/libgit2/libgit2/issues/4230?

**Comment by deathlyfrantic** [comment]
Sorry, I have absolutely no idea. Is it still slow with "default" zsh color codes? Have you tried it in different repos? I have trouble seeing how this could be caused by this prompt thing - it just doesn't do enough - so I'm guessing it's something up with libgit2.

**Comment by mathomp4** [comment]
No. Changing the colors to the zsh ones didn't seem to make a difference. I'll try the straight ANSI tomorrow.

**Comment by deathlyfrantic** [comment]
Also try it in a couple different repos. I guess if you're using it in like, the Linux kernel git repo or something, maybe having a billionty files and tons of history might slow it down, though I really don't think it would be that slow. Could also run it through strace to see if there are any syscalls that obviously jump out as being the culprit.
